export interface AccountInterface {
    address: string
    airlineCode: string
    aptUnit: string
    billDate: any
    birthDate: Date
    boardingPriority: string
    city: string
    costCenterCode: any
    country: string
    deleted: boolean
    departmentName: string
    employeeNumber: string 
    employmentStatus: string
    employmentType: string
    facebook: any
    firstName: string
    fqtvNumber: string
    fromAffiliate: number
    gender: string
    hireDate: Date
    homePhone: string
    id: number
    id90InvitesUsed: string
    id90Status: string
    idMembers: number
    inviteCode: string
    invitedByUserId: any
    jobTitleDesc: string
    knownTravelerNumber: string
    lastName: string
    linkedin: any
    membershipType: string
    middleName: string
    mobilePhone: string
    organizationId: number
    passportCountryBirth: string
    passportExpirationDate: Date
    passportFirstName: string
    passportIssuanceCountry: string
    passportIssuanceDate: Date
    passportLastName: string
    passportMiddleName: string
    passportNationality: string
    passportNumber: string
    passportNumberDomestic: string
    personalEmail: string
    personalId: string
    promoCode: any
    rebillAvoid: string
    rebillDate: any
    roleName: any
    seniorityDate: Date
    signupDate: Date
    state: string
    travelStatus: string
    trebecaInvitesRemaining: number
    trebecaInvitesUsed: number
    twitter: any
    workEmail: string
    worksInAirline: string
    ytdSavings: number
    zip: string
}
